repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: requirements-txt-fixer

-   repo: git://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
    - id: python-safety-dependencies-check
      files: requirements.txt
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
        - id: flake8
