version: "3.9"
services:
  mastermind:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - ${PWD}/config.yaml:/etc/app/config.yaml
    environment:
      - API_KEYS=1234
      - CONFIG_PATH=/etc/app/config.yaml
      - ENV=dev
      - DB_CONN_STR=postgresql://postgres:postgres@db:5432/
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
